model: topomoe_tiny_2s_patch16_128
mlp_conserve: true
wiring_lambd: 0.01
desc: >
  Two stage topomoe, conserved params.
  Don't add pos embedding to pooled input.
  With wiring cost 0.01.

dataset: hfds/clane9/imagenet-100
scale: [0.33334, 1.0]
hflip: 0.5
color_jitter: 0.4
in_memory: true
epochs: 50

amp: true
wandb: true
debug: false
