model: vision_transformer_tiny_patch16_128
mlp_ratio: 1.0
mlp_rank: "4"
desc: "ViT MLP ratio 1, SuMoE rank 4"

dataset: imagenet-100
crop_min_scale: 0.33334
hflip: 0.5
color_jitter: 0.4
epochs: 50
amp: true
wandb: true
figure_interval: 5
