model: vision_transformer_tiny_patch16_128
untied: "1,0,0"
desc: "untied norm weights"

dataset: micro-imagenet-100
epochs: 10
decay_lr: false
warmup_fraction: 0.0
weight_decay: 0.0
amp: true
wandb: true
figure_interval: 1
