model: vision_transformer_tiny_patch16_128
untied: "1,1,1"
mlp_ratio: 0.166667
lr: 1.0e-04
desc: "all untied weights with bottleneck mlp and lower lr"

dataset: imagenet-100
crop_min_scale: 0.33334
hflip: 0.5
color_jitter: 0.4
epochs: 50
amp: true
wandb: true
figure_interval: 5
