model: topomoe_tiny_3s_patch16_128
mlp_conserve: true
static_pool: false
# adjust lambda to be consistent with last runs
# since I changed from average to sum
wiring_lambd: 0.014
desc: >
  Three stage topomoe, conserved params, dynamic pool,
  wiring cost 0.014 (0.1 / 7)

dataset: hfds/clane9/imagenet-100
scale: [0.33334, 1.0]
hflip: 0.5
color_jitter: 0.4
in_memory: true
epochs: 50

amp: true
wandb: true
debug: false
